### PR TITLE
Contributing guide local setup

### PR DESCRIPTION
**Pull request by makalaaneesh**
Issue https://github.com/dvargas92495/roam-js-extensions/issues/63

### CODE REVIEW

**Review by dvargas92495 — APPROVED** [review]
Add "(Closes #63)" to your initial commit message and it will automatically close the issue!

**Comment by makalaaneesh** [comment]
@dvargas92495 Looks like I can't really merge because the deploy check fails. 
Curios to understand this. How are the secrets injected?

**Comment by dvargas92495** [comment]
Oh you can't merge because I'm the repo owner haha.

I'll merge, but in future PRs, add the `Close #${issuenumber}` so that merges close said issue

**Comment by dvargas92495** [comment]
I have a task already created to investigate lambda deploys from forked repos

**Pull request merged**
